name: evalzoo
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=23.0.1
  - conda-forge::numpy=1.24.2
  - conda-forge::pandas=1.5.3
  - conda-forge::r-base=4.2.3
  - conda-forge::r-essentials=4.2
  - conda-forge::r-ggplot2=3.4.1
  - conda-forge::r-lazyeval=0.2.2
  - conda-forge::r-pillar=1.8.1
  - conda-forge::r-rcolorbrewer=1.1-3
  - conda-forge::r-viridis=0.6.2
  - conda-forge::r-skimr=2.1.5
  - conda-forge::r-devtools=2.4.5
  - rpy2
  - ipykernel
